version: "3"

services:
  contracts:
    build: ./contracts
    network_mode: host
    depends_on:
      hardhat:
        condition: service_healthy
    environment:
      - CONTRACTS=TrustAndTeach
      - RPC_URL=http://localhost:8545
      - MNEMONIC=test test test test test test test test test test test junk
      - NETWORK=localhost
    volumes:
      - ./deployments:/opt/contracts/deployments

  dispatcher:
    depends_on:
      contracts:
        condition: service_completed_successfully

  state_server:
    depends_on:
      contracts:
        condition: service_completed_successfully

  deployer:
    depends_on:
      contracts:
        condition: service_completed_successfully